    notes: |-
      # Manage your Spinnaker
      [Open Cloud Shell](https://console.cloud.google.com/cloudshell/editor?shellonly=true&cloudshell_git_repo=https://github.com/GoogleCloudPlatform/spinnaker-for-gcp.git&cloudshell_working_dir=scripts/manage&cloudshell_tutorial=landing_page_expanded.md)

      Ensure you are connected to the correct GKE Cluster from within Cloud Shell:
      ```
      gcloud container clusters get-credentials $GKE_CLUSTER --zone $ZONE --project $PROJECT_ID
      ```

      # Connect to your Spinnaker
      Follow the link above to establish port forwarding via Cloud Shell. Note that you can securely expose your Spinnaker via that link as well so it can be directly accessed in the future.

      # View the who, what, when and where of your Spinnaker installation
      [Spinnaker Audit Log](https://console.developers.google.com/logs/viewer?project=$PROJECT_ID&resource=cloud_function&logName=projects%2F$PROJECT_ID%2Flogs%2F$CLOUD_FUNCTION_NAME&minLogLevel=200)

      # Config Backups
      Full backups are stored in [this bucket](https://console.developers.google.com/storage/browser/$BUCKET_NAME/backups/?project=$PROJECT_ID).
